#include "music.h"

struct noteData track[] = {
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "SA" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "KU" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "RA" },

    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "SA" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "KU" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "RA" },

    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "YA" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "YO" },
    { .note = NOTE_C, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "I" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "NO" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "SO" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 50,  .lyric = "RA" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 50,  .lyric = "-" },
    { .note = NOTE_F, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "WA" },

    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "MI" },
    { .note = NOTE_D, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "WA" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "TA" },
    { .note = NOTE_F, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "SU" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "KA" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 50,  .lyric = "GI" },
    { .note = NOTE_C, .octave = A8, .duration = DURATION_QUARTER, .length = 50,  .lyric = "-" },
    { .note = NOTE_B, .octave = A8, .duration = DURATION_HALF,    .length = 200, .lyric = "RI" },

    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "KA" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "SU" },
    { .note = NOTE_C, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "MI" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "KA" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "KU" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 50,  .lyric = "MO" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 50,  .lyric = "-" },
    { .note = NOTE_F, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "KA" },

    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "NI" },
    { .note = NOTE_D, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "O" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "I" },
    { .note = NOTE_F, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "ZO" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "I" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 50,  .lyric = "ZU" },
    { .note = NOTE_C, .octave = A8, .duration = DURATION_QUARTER, .length = 50,  .lyric = "-" },
    { .note = NOTE_B, .octave = A8, .duration = DURATION_HALF,    .length = 200, .lyric = "RU" },

    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "I" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "ZA" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "YA" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "I" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 100, .lyric = "ZA" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "YA" },

    { .note = NOTE_E, .octave = A7, .duration = DURATION_QUARTER, .length = 200, .lyric = "MI" },
    { .note = NOTE_F, .octave = A7, .duration = DURATION_QUARTER, .length = 200, .lyric = "NI" },
    { .note = NOTE_B, .octave = A7, .duration = DURATION_QUARTER, .length = 150, .lyric = "YU" },
    { .note = NOTE_A, .octave = A7, .duration = DURATION_QUARTER, .length = 150, .lyric = "-" },
    { .note = NOTE_F, .octave = A7, .duration = DURATION_QUARTER, .length = 200, .lyric = "KA" },
    { .note = NOTE_E, .octave = A7, .duration = DURATION_HALF,    .length = 200, .lyric = "N" },
};